### ISSUE TITLE
FR: additional hotkeys list filters

### ISSUE THREAD

**Issue by Randy-Astle** [pjeby/hotkey-helper#11]
Now that I know that only some of the capabilities were sherlocked, I read through the documentation more thoroughly. I definitely have some use for the plugin.

IMO, it would be useful to be able to apply two filters to the list of hotkeys:
1) Allow the user to enter a key or chord as text and find all commands that use that key or chord (e.g. ALT + S, or just ALT to list all commands that require the ALT key)
2) Display only the commands that have hotkeys assigned to them

**Comment by pjeby** [comment]
That sounds like you're looking for [the Keyboard Analyzer plugin](https://github.com/cogscides/obsidian-keyboard-analyzer).

**Comment by Randy-Astle** [comment]
Thanks! :-)

Looks like it has the functionality I have been looking for.
