### ISSUE TITLE
seems to break plugins annotation plugin

### ISSUE THREAD

**Issue by ksdavidc** [pjeby/hotkey-helper#14]
see attached 
[test annotations.zip](https://github.com/user-attachments/files/17436816/test.annotations.zip)
and here 
https://github.com/alberti42/obsidian-plugins-annotations/issues/5#issuecomment-2422593980

**Comment by ksdavidc** [comment]
It appears that we might have a clue to the source of the problem, thanks to the plugins annotations developer:

> Ok. I did some more debugging of the Hotkey plugin. ...The problem is in the following function. I copy the entire function here, but you only have to appreciate a couple of points I will comment about later
> 
> ```ts
>  // Add top-level items (search and pseudo-plugins)
>     addGlobals(tabId: string, settingEl: HTMLDivElement) {
>         this.globalsAdded = true;
> 
>         // Add a search filter to shrink plugin list
>         const containerEl = settingEl.parentElement;
>         let searchEl: SearchComponent;
>         if (tabId !== "plugins" || this.searchInput) {
>             // Replace the built-in search handler
>             (searchEl = this.searchInput)?.onChange(changeHandler);
>         } else {
>             const tmp = new Setting(containerEl).addSearch(s => {
>                 searchEl = s;
>                 s.setPlaceholder("Filter plugins...").onChange(changeHandler);
>             });
>             searchEl.containerEl.style.margin = "0";
>             containerEl.createDiv("hotkey-search-container").append(searchEl.containerEl);
>             tmp.settingEl.detach();
>         }
>         if (tabId === "community-plugins") {
>             searchEl.inputEl.addEventListener("keydown", e => {
>                 if (e.keyCode === 13 && !Keymap.getModifiers(e)) {
>                     this.gotoPlugin();
>                     return false;
>                 }
>             })
>         }
>         const plugin = this;
>         function changeHandler(seek: string){
>             const find = (plugin.lastSearch[tabId] = seek).toLowerCase();
>             function matchAndHighlight(el: HTMLElement) {
>                 if (!el) return false;
>                 const text = el.textContent = el.textContent; // clear previous highlighting, if any
>                 const index = text.toLowerCase().indexOf(find);
>                 if (!~index) return false;
>                 el.textContent = text.substr(0, index);
>                 el.createSpan("suggestion-highlight").textContent = text.substr(index, find.length);
>                 el.insertAdjacentText("beforeend", text.substr(index+find.length))
>                 return true;
>             }
>             containerEl.findAll(".setting-item").forEach(e => {
>                 const nameMatches = matchAndHighlight(e.find(".setting-item-name"));
>                 const descMatches = matchAndHighlight(
>                     e.find(".setting-item-description > div:last-child") ??
>                     e.find(".setting-item-description")
>                 );
>                 const authorMatches = matchAndHighlight(
>                     e.find(".setting-item-description > div:nth-child(2)")
>                 );
>                 e.toggle(nameMatches || descMatches || authorMatches);
>             });
>         }
>         defer(() => {
>             if (!searchEl) return
>             if (searchEl && typeof plugin.lastSearch[tabId] === "string") {
>                 searchEl.setValue(plugin.lastSearch[tabId]);
>                 searchEl.onChanged();
>             }
>             if (!Platform.isMobile) searchEl.inputEl.select();
>         });
>         containerEl.append(settingEl);
> 
>         if (tabId === "plugins") {
>             const editorName    = this.getSettingsTab("editor")?.name || "Editor";
>             const workspaceName = this.getSettingsTab("file")?.name   || "Files & Links";
>             this.createExtraButtons(
>                 new Setting(settingEl.parentElement)
>                     .setName("App").setDesc("Miscellaneous application commands (always enabled)"),
>                 {id: "app", name: "App"}, true
>             );
>             this.createExtraButtons(
>                 new Setting(settingEl.parentElement)
>                     .setName(editorName).setDesc("Core editing commands (always enabled)"),
>                 {id: "editor", name: editorName}, true
>             );
>             this.createExtraButtons(
>                 new Setting(settingEl.parentElement)
>                     .setName(workspaceName).setDesc("Core file and pane management commands (always enabled)"),
>                 {id: "workspace", name: workspaceName}, true
>             );
>             settingEl.parentElement.append(settingEl);
>         }
>     }
> ```
> 
> The problem is with the lines of code:
> 
> ```ts
> // Replace the built-in search handler
>             (searchEl = this.searchInput)?.onChange(changeHandler);
> ```
> 
> It totally replaces the original Obisidian handler for the visualization of the search results with a new function:
> 
> ```ts
> function changeHandler(seek: string){
>             const find = (plugin.lastSearch[tabId] = seek).toLowerCase();
>             function matchAndHighlight(el: HTMLElement) {
>                 if (!el) return false;
>                 const text = el.textContent = el.textContent; // clear previous highlighting, if any
>                 const index = text.toLowerCase().indexOf(find);
>                 if (!~index) return false;
>                 el.textContent = text.substr(0, index);
>                 el.createSpan("suggestion-highlight").textContent = text.substr(index, find.length);
>                 el.insertAdjacentText("beforeend", text.substr(index+find.length))
>                 return true;
>             }
>             containerEl.findAll(".setting-item").forEach(e => {
>                 const nameMatches = matchAndHighlight(e.find(".setting-item-name"));
>                 const descMatches = matchAndHighlight(
>                     e.find(".setting-item-description > div:last-child") ??
>                     e.find(".setting-item-description")
>                 );
>                 const authorMatches = matchAndHighlight(
>                     e.find(".setting-item-description > div:nth-child(2)")
>                 );
>                 e.toggle(nameMatches || descMatches || authorMatches);
>             });
>         }
> ```
> 
> This way of coding is dangerous because it has hard-coded a pseudo duplicate of the original Obsidian code, with some patches...

**Comment by pjeby** [comment]
Fixed in version 0.3.19.

Please note that HH is an older plugin that was written *before* Obsidian had the nice little buttons -- that was a feature directly inspired by Hotkey Helper.  But they didn't copy the whole thing, as Obsidian *doesn't* show hotkey counts and conflicts the way HH does!

The clash over search is precisely because of this feature: when Obsidian added in its own nice little buttons, they didn't include hotkey conflict management, and they changed the search to re-render all the plugins, which broke HH's coloring and tooltips.  So I had to put back Obsidian's older way of plugin searching in order to put back HH's hotkey info in a timely fashion.

**Comment by pjeby** [comment]
Now that HH doesn't break the other plugin, I discovered that [the other plugin is breaking Hotkey Helper](https://github.com/alberti42/obsidian-plugins-annotations/issues/14).  With it installed and enabled, some HH features I use regularly do not work properly.  So be aware that there's still an incompatibility, but this one is on the other plugin's side.
