### ISSUE TITLE
0.3.19 Hotkeys Settings Not Opening

### ISSUE THREAD

**Issue by ChuckWheat** [pjeby/hotkey-helper#15]
0.3.19 on a fresh vault does not create a visible interface for:
"Hotkey Helper: Open hotkeys for plugin..."
"Hotkey Helper: Open settings for plugin..."

Whereas 0.3.18 does create the visible interface.

"Hotkey Helper: Open the Community Plugins settings"
"Hotkey Helper: Browse or search the Community Plugins catalog"
Both behave as expected on 0.3.19

**Comment by pjeby** [comment]
Thanks for the report!  The issue should be fixed with 0.3.20.
