### ISSUE TITLE
Hotkey icons missing in the Community plugins tab

### ISSUE THREAD

**Issue by zzdcgg** [pjeby/hotkey-helper#2]
Hi @pjeby, the hotkey icons show up in the Core plugins tab, but none of them show up in the Community plugins tab (see screenshots below).  How can I fix this?  Thanks!

![image](https://user-images.githubusercontent.com/70086177/117648178-7d5cc100-b1c0-11eb-9f74-303876d03341.png)
![image](https://user-images.githubusercontent.com/70086177/117648255-949bae80-b1c0-11eb-9bd8-2b1991874efa.png)
![image](https://user-images.githubusercontent.com/70086177/117648325-aa10d880-b1c0-11eb-8d13-fede6ea3a32d.png)

**Comment by pjeby** [comment]
I'm guessing you're using the new search filter in the insider build; it's not currently compatible with hotkey-helper, as searching deletes all the setting controls and recreates them.  There's a workaround in 0.3.0, which I've just released and should be available via update now.

**Comment by zzdcgg** [comment]
Hi @pjeby - just installed 0.3.0 but the issue remains the same.  Not sure if it is connected to the Obsidian v0.12.3 update...

**Comment by pjeby** [comment]
Yes, it is.  See #3 for the details.  0.3.1 has been released with a fix.

**Comment by zzdcgg** [comment]
It is working now. Thanks!
