### ISSUE TITLE
[0.12.3] Plugin works on Core Plugins now but not Community Plugins

### ISSUE THREAD

**Issue by apotenza92** [pjeby/hotkey-helper#3]
For some reason after upgrading to Obsidian v0.12.3 this plugin now only works on Core Plugins (which is new and unexpected), but does not work anymore on Community Plugins.

**Comment by zzdcgg** [comment]
Same issue here..

**Comment by pjeby** [comment]
Have you updated the plugin to 0.3.0?

**Comment by apotenza92** [comment]
Yes

**Comment by pjeby** [comment]
Ok, it turns out that 0.12.3 changed the tab's internal id from `third-party-plugins` to `community-plugins`.  0.3.1 has the fix, so update and you should be fine.

**Comment by apotenza92** [comment]
Great thanks!
