### ISSUE TITLE
Buttons need padding in plugin modal

### ISSUE THREAD

**Issue by Ampa** [pjeby/hotkey-helper#4]
Thanks for the handy plugin!

![image](https://user-images.githubusercontent.com/1459388/118803742-a4d81b80-b89b-11eb-8f6a-da35c90ddda3.png)
![image](https://user-images.githubusercontent.com/1459388/118803792-b5889180-b89b-11eb-9bf1-ae03e488c6a2.png)

**Very** minor issue, but when the window is narrow, the buttons wrap and crash into each other.

**Comment by pjeby** [comment]
Fixed in 0.3.6

**Comment by Ampa** [comment]
Awesome - looks much better :)

**Comment by pjeby** [comment]
Did you find this issue on mobile, by any chance?  I haven't had a chance yet to see how well the plugin works on mobile, especially for my recent feature additions.
