### ISSUE TITLE
[BUG] Cause duplicate search Input box After ver. 0.12.12

### ISSUE THREAD

**Issue by Quorafind** [pjeby/hotkey-helper#5]
![image](https://user-images.githubusercontent.com/13215013/127251864-77f19105-ae06-4011-93f4-19a6c9f1b739.png)

https://user-images.githubusercontent.com/13215013/127252220-4830efa4-57bc-4e0b-b439-305401b4f284.mp4

**Comment by pjeby** [comment]
Fixed in 0.3.7.  Thanks for reminding me, I'd forgotten about this change being needed.
