### ISSUE TITLE
[Bug]: `Options` and `Hotkeys` Buttons are not showing when using new Obsidian 0.13's URL Scheme

### ISSUE THREAD

**Issue by chrisgrieser** [pjeby/hotkey-helper#7]
Using the new URL Scheme provided since Obsidian 0.13+, for example, `obsidian://show-plugin?id=dataview` will result in the `Options` and `Hotkeys` Buttons being missing.

When using the URL Scheme provided by the Hotkey Helper (or simply clicking `Browse` in the Settings), the buttons do appear.
`obsidian://goto-plugin?id=dataview`

Demovideo here (sorry for the bad quality, without compression the video was too big)
![Screen Recording 2022-01-10 at 18 36 10](https://user-images.githubusercontent.com/73286100/148812820-e0b2460e-bd11-4f01-abdf-612bcfe366c6.gif)

**Comment by pjeby** [comment]
Eh, technically not a bug, but a new feature.  ;-)  Implemented in 0.3.9, though.

**Comment by chrisgrieser** [comment]
fantastic, thanks for the quick fix! :)
